मुंतजिर रहा मैं तेरी एक तबस्सुम के लिए
तूने बे सबब खतूत भेज दिया मेरे फ़स्ख़-ए-निकाह का
बेगैरत है खुशी भी न देख सही अपने जहां पनाह का
वैसे कुछ भी साकी बनके न होगा कुछ अहवाल का
जा खुद रफ्तगी हा ए हैरत मुझे फिक्र नहीं है मलामत का
जम जम खिदमत किया तेरी दस्त ए कैस बनकर
जा जीले अपनी क़ुव्वत-ए-'अमल और ऐश कर 
